language: r
os: linux
dist: xenial

r:
- oldrel
- release
- devel

before_install: cd analysis
  - sudo apt-get update
  - sudo apt-get install libgdal-dev libproj-dev
  - sudo apt install -y libudunits2-0 libudunits2-dev


install: skip

script:
  - R -e "source('../tests/testthat.R')"
