language: r
os: linux
dist: xenial
r:
  - oldrel
  - release
  - devel

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'

script:
  - R -e "source('tests/testthat.R')"
