language: r
os: linux
dist: xenial

r:
- oldrel
- release
- devel

before_install:
  - sudo apt-get update
  - sudo apt-get install libgdal-dev libproj-dev libxml2-dev libssl-dev
  - sudo apt install -y libudunits2-0 libudunits2-dev
  - cd analysis


install: skip

script:
  - R -e "source('../tests/testthat.R')"
