---
output:
  pdf_document:
    citation_package: natbib
    keep_tex: false
    latex_engine: xelatex
title: "Nest Provisioning in a Fire Disturbed Landscape"
author: "Eliza Stein"
date: "11/8/2020"
bibliography: references.bib
csl: './apa.csl'
---

# Introduction

Fire plays an important role as a consistent disturbance in maintaining open stands of old-growth Ponderosa Pine (*Pinus ponderosa*) forests by helping to eliminate understory and limit fuel loads [@veblen2000climatic]. Before human intervention, Ponderosa Pine forests naturally underwent forest fires in 5-50 year intervals [@veblen2000climatic]. Over the past century, however, tree planting initiatives and increased implementation of fire suppression have led to increased density of stands [@griffis2001understory], making forest stands that are already drought stressed even more susceptible to high severity crown fires [@veblen2000climatic]. In 2002, a human-caused wildfire, the Hayman Fire, burned 138,000 acres of old-growth Ponderosa pine forests in Colorado's Pike National Forest [@graham2003hayman]. 

The Flammulated Owl (*Psiloscops flammeolus*) is a territorial, insectivorous, and nocturnal raptor native to montane forests in portions of the Rocky Mountains, Sierra Nevada Mountains, and the Occidental Mountains [@linkhart2013flammulated]. The diet of the owl primarily consists of moths native to these regions [@linkhart2013flammulated]. As a highly specialized secondary cavity nesting raptor, the Flammulated Owl is deemed an indicator species, meaning that the health of an ecosystem can be estimated based on the health of their population. Survival models have shown that Flammulated Owl survival in the HFSA is currently lower than survival in MGSA, suggesting that mortality, rather than emigration, explains most of the population declines following the Hayman Fire (Linkhart and Yanco, unpublished data).

Here, I examine one possible explanation for increased mortality in HFSA: prey availability. High severity burns dramatically alter vegetation structure, which in turn alters insect communities. Over time, insect communities within high intensity burn scars can crash, leaving avian predators without important food resources [@nappi2010effect]. If Flammulated Owls are adapting their behavior in response to changing prey availability, I would expect that the rate of prey deliveries to active nests would increase or decrease (increase if prey is lower quality, decrease if prey is more scarce or difficult to detect) [@zarybnicka2009tengmalm]. If Flammulated Owls are not adapting their behavior, this could mean that prey availability has either not changed or, more likely, that Flammulated Owls, which do not occupy landscapes prone to high severity burns, do not adapt their behavior in response to large-scale landscape changes.